spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: dm.jdbc.driver.DmDriver
    druid:
      master:
        url: jdbc:dm://172.26.46.25:5236/DAMENG?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=utf-8&clobAsString=true
        username: ${DB_USERNAME:CLOUDWALK}
        password: ${DB_PASSWORD:chds1qaz@WSX}
      initialSize: 5
      minIdle: 10
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,slf4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

  # Spring Batch配置
  batch:
    jdbc:
      initialize-schema: always
      schema: classpath:org/springframework/batch/core/schema-dm.sql
      table-prefix: BATCH_
    job:
      enabled: false  # 禁止启动时自动执行Job

  sql:
    init:
      platform: dm
      mode: always
      schema-locations:
        - classpath:org/springframework/batch/core/schema-dm.sql 