-- 告警处理记录表
CREATE TABLE IF NOT EXISTS ALERT_HANDLING_RECORD (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    ALERT_ID BIGINT NOT NULL,
    HANDLER VARCHAR(100) NOT NULL,
    DESCRIPTION TEXT,
    HANDLE_TIME TIMESTAMP,
    CREATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
); 