CREATE TABLE "CLOUDWALK"."ALERT_HANDLE_RECORD"
(
"ID" BIGINT IDENTITY(1, 1) NOT NULL,
"ALERT_ID" BIGINT NOT NULL,
"HANDLER" VARCHAR(50) NOT NULL,
"HANDLE_TIME" TIMESTAMP(6) NOT NULL,
"BEFORE_STATUS" INT NOT NULL,
"AFTER_STATUS" INT NOT NULL,
"REMARK" TEXT,
"CREATE_TIME" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
"UPDATE_TIME" TIMESTAMP(6) DEFAULT SYSTIMESTAMP,
NOT CLUSTER PRIMARY KEY("ID")) STORAGE(ON "CLOUDWALK", CLUSTERBTR);

COMMENT ON COLUMN CLOUDWALK.ALERT_HANDLE_RECORD."ALERT_ID" IS '告警ID';
COMMENT ON COLUMN CLOUDWALK.ALERT_HANDLE_RECORD."HANDLER" IS '处理人';
COMMENT ON COLUMN CLOUDWALK.ALERT_HANDLE_RECORD."HANDLE_TIME" IS '处理时间';
COMMENT ON COLUMN CLOUDWALK.ALERT_HANDLE_RECORD."BEFORE_STATUS" IS '处理前状态';
COMMENT ON COLUMN CLOUDWALK.ALERT_HANDLE_RECORD."AFTER_STATUS" IS '处理后状态';
COMMENT ON COLUMN CLOUDWALK.ALERT_HANDLE_RECORD."REMARK" IS '处理备注';

-- 添加外键约束
ALTER TABLE "CLOUDWALK"."ALERT_HANDLE_RECORD" ADD CONSTRAINT "FK_ALERT_HANDLE_RECORD_ALERT_ID" 
FOREIGN KEY ("ALERT_ID") REFERENCES "CLOUDWALK"."ALERT" ("ID"); 